# Generated by Django 5.2.5 on 2025-08-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_department_options_profile_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
