# Generated by Django 5.2.5 on 2025-08-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='created_at',
            new_name='enrolled_at',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='progress_percent',
            new_name='progress',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_external_allowed',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='completed_on',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='external',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='external_note',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='course',
            name='allow_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
