# Generated by Django 5.2.5 on 2025-08-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_course_options_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='allow_external',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.AddField(
            model_name='course',
            name='delivered_by_external',
            field=models.BooleanField(default=False, verbose_name='Delivered by external company'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
