# Generated by Django 5.2.5 on 2025-08-13 08:24

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.course'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(upload_to=core.models.course_material_upload_to),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
