# Generated by Django 5.2.5 on 2025-08-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_coursematerial_course_alter_coursematerial_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
