# Generated by Django 5.2.5 on 2025-08-13 11:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_materialprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='kind',
            field=models.CharField(choices=[('FILE', 'File'), ('YOUTUBE', 'YouTube')], default='FILE', max_length=20),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='materialprogress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='materialprogress',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coursematerial'),
        ),
    ]
