# Generated by Django 5.2.5 on 2025-08-15 11:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_coursematerial_kind_coursematerial_youtube_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialprogress',
            old_name='seconds_watched',
            new_name='last_position_seconds',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='original_name',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='youtube_url',
        ),
        migrations.RemoveField(
            model_name='materialprogress',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='materialprogress',
            name='percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('LEARNER', 'Learner')], default='LEARNER', help_text='Access level for this user.', max_length=16),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.material_upload_to),
        ),
        migrations.AlterField(
            model_name='materialprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
