# Generated by Django 5.2.5 on 2025-08-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_seconds_watched_materialprogress_last_position_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.course'),
        ),
    ]
