# Generated by Django 5.2.5 on 2025-08-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_coursematerial_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='kind',
            field=models.CharField(choices=[('FILE', 'File'), ('YOUTUBE', 'Link')], default='FILE', max_length=12),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
